/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ThongBaoDAO;
import DAO.TinNhanDAO;
import DTO.ThongBaoDTO;
import DTO.TinNhanDTO;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.CallableStatement; 
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author ASUS
 */
public class AdminHomepage extends javax.swing.JFrame {
    private Connection connection;
    public static String ghichu;

    /**
     * Creates new form AdminHomepage
     */
    public AdminHomepage() {
        initComponents();
        setLocationRelativeTo(null);
        connectToDatabase();
        loadUserData();
        addTableClickListener();
        displayMessages();
        TF_getEmailAD.setText(DangNhap.pEmail);
        TF_getTenAD.setText(getTenAdmin(DangNhap.pEmail));
    }
    private String getTenAdmin(String adminEmail) {
        String tenAdmin = "";
        if (connection != null) {
            try {
                String sql = "SELECT TENAD FROM AD WHERE EMAILAD = ?";
                PreparedStatement pstmt = connection.prepareStatement(sql);
                pstmt.setString(1, adminEmail);

                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    tenAdmin = rs.getString("TENAD");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    connection.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        return tenAdmin;
    }

    private void connectToDatabase(){
         // Kết nối đến cơ sở dữ liệu
            try{
               Class.forName("oracle.jdbc.driver.OracleDriver");
               connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##tictac", "tictac");
            } catch (ClassNotFoundException | SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "ko the ket noi dc");
                
            }    
    }
    
    private void loadUserData(){
         try {
            String sql = "SELECT EMAILND, TENND FROM NGUOIDUNG";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) table_dsND.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                String email = resultSet.getString("EMAILND");
                String tenND = resultSet.getString("TENND");
                model.addRow(new Object[]{email, tenND});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu người dùng!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void addTableClickListener() {
        table_dsND.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = table_dsND.getSelectedRow();
                if (row >= 0) {
                    String email = (String) table_dsND.getValueAt(row, 0);
                    String tenND = (String) table_dsND.getValueAt(row, 1);
                    jTextField2.setText(email);
                    TF_tenND.setText(tenND);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_DX_TicTac = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel_quanlitaikhoan = new javax.swing.JPanel();
        tf_nhaptenNDcantim = new javax.swing.JTextField();
        btn_searchND = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dsND = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_tenND = new javax.swing.JTextField();
        btn_suaND = new javax.swing.JButton();
        btn_xoaND = new javax.swing.JButton();
        panel_TK = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_getTenAD = new javax.swing.JTextField();
        TF_getEmailAD = new javax.swing.JTextField();
        btn_DoiPass_TK = new javax.swing.JButton();
        jpanel_ThongBao = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_thongbao = new javax.swing.JTextArea();
        btn_Taothongbao = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_thongbao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TicTac");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork (2).png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(30, 136, 229));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quản lí người dùng");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(30, 136, 229));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tài khoản");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_DX_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DX_TicTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-out.png"))); // NOI18N
        btn_DX_TicTac.setText("Đăng xuất");
        btn_DX_TicTac.setToolTipText("");
        btn_DX_TicTac.setActionCommand("");
        btn_DX_TicTac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DX_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DX_TicTacMouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chat (1).png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(30, 136, 229));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tạo thông báo");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btn_DX_TicTac)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(btn_DX_TicTac)
                .addGap(85, 85, 85))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new java.awt.CardLayout());

        panel_quanlitaikhoan.setBackground(new java.awt.Color(253, 253, 223));

        tf_nhaptenNDcantim.setBackground(new java.awt.Color(182, 231, 245));

        btn_searchND.setBackground(new java.awt.Color(26, 55, 245));
        btn_searchND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_searchND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchNDActionPerformed(evt);
            }
        });

        table_dsND.setBackground(new java.awt.Color(182, 231, 245));
        table_dsND.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Email", "Tên người dùng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_dsND);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jTextField2.setBackground(new java.awt.Color(182, 231, 245));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên người dùng");

        TF_tenND.setBackground(new java.awt.Color(182, 231, 245));
        TF_tenND.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_suaND.setBackground(new java.awt.Color(26, 55, 245));
        btn_suaND.setForeground(new java.awt.Color(255, 255, 255));
        btn_suaND.setText("Sửa");
        btn_suaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaNDActionPerformed(evt);
            }
        });

        btn_xoaND.setBackground(new java.awt.Color(26, 55, 245));
        btn_xoaND.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaND.setText("Xóa");
        btn_xoaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaNDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_quanlitaikhoanLayout = new javax.swing.GroupLayout(panel_quanlitaikhoan);
        panel_quanlitaikhoan.setLayout(panel_quanlitaikhoanLayout);
        panel_quanlitaikhoanLayout.setHorizontalGroup(
            panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(tf_nhaptenNDcantim, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_searchND, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                                .addComponent(TF_tenND)
                                .addGap(84, 84, 84)))
                        .addGap(53, 53, 53)
                        .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_suaND, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoaND, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panel_quanlitaikhoanLayout.setVerticalGroup(
            panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_searchND)
                    .addComponent(tf_nhaptenNDcantim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_quanlitaikhoanLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_quanlitaikhoanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_suaND)))
                .addGap(18, 18, 18)
                .addGroup(panel_quanlitaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_tenND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaND))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel2.add(panel_quanlitaikhoan, "card2");

        panel_TK.setBackground(new java.awt.Color(253, 253, 223));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Tên admin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Email admin");

        TF_getTenAD.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TF_getTenAD.setText("ten admin");
        TF_getTenAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_getTenADActionPerformed(evt);
            }
        });

        TF_getEmailAD.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TF_getEmailAD.setText("email admin");

        btn_DoiPass_TK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_DoiPass_TK.setText("Đổi mật khẩu");
        btn_DoiPass_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DoiPass_TKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_TKLayout = new javax.swing.GroupLayout(panel_TK);
        panel_TK.setLayout(panel_TKLayout);
        panel_TKLayout.setHorizontalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_getEmailAD, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(TF_getTenAD))
                .addGap(193, 193, 193))
            .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TKLayout.createSequentialGroup()
                    .addGap(327, 327, 327)
                    .addComponent(btn_DoiPass_TK)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );
        panel_TKLayout.setVerticalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TF_getTenAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_getEmailAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(456, Short.MAX_VALUE))
            .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TKLayout.createSequentialGroup()
                    .addGap(307, 307, 307)
                    .addComponent(btn_DoiPass_TK)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_TK, "card3");

        jpanel_ThongBao.setBackground(new java.awt.Color(253, 253, 223));

        txtA_thongbao.setColumns(20);
        txtA_thongbao.setRows(5);
        jScrollPane2.setViewportView(txtA_thongbao);

        btn_Taothongbao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Taothongbao.setText("Tạo");
        btn_Taothongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaothongbaoActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(204, 255, 255));

        panel_thongbao.setBackground(new java.awt.Color(204, 255, 255));
        panel_thongbao.setLayout(new java.awt.GridBagLayout());
        jScrollPane3.setViewportView(panel_thongbao);

        javax.swing.GroupLayout jpanel_ThongBaoLayout = new javax.swing.GroupLayout(jpanel_ThongBao);
        jpanel_ThongBao.setLayout(jpanel_ThongBaoLayout);
        jpanel_ThongBaoLayout.setHorizontalGroup(
            jpanel_ThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThongBaoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jpanel_ThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_ThongBaoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_Taothongbao)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jpanel_ThongBaoLayout.setVerticalGroup(
            jpanel_ThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_ThongBaoLayout.createSequentialGroup()
                .addGroup(jpanel_ThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_ThongBaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_ThongBaoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_Taothongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.add(jpanel_ThongBao, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        panel_quanlitaikhoan.setVisible(true);
        panel_TK.setVisible(false);
        jpanel_ThongBao.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        panel_quanlitaikhoan.setVisible(false);
        panel_TK.setVisible(true);
        jpanel_ThongBao.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void TF_getTenADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_getTenADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_getTenADActionPerformed

    private void btn_DoiPass_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoiPass_TKMouseClicked
        NhapEmail ne = new NhapEmail();
        ne.show();
        dispose();
    }//GEN-LAST:event_btn_DoiPass_TKMouseClicked

    private void btn_DX_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DX_TicTacMouseClicked
        DangNhap dn = new DangNhap();
        dn.show();
        dispose();
    }//GEN-LAST:event_btn_DX_TicTacMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_suaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaNDActionPerformed
        // TODO add your handling code here:
        String email = jTextField2.getText();
        String tenND = TF_tenND.getText();

    // Kiểm tra nếu các JTextField không rỗng
        if (email.isEmpty() || tenND.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Kết nối tới cơ sở dữ liệu
    connectToDatabase();

    if (connection != null) {
        try {
            // Tạo câu lệnh SQL để cập nhật tên người dùng
            String sql = "UPDATE NGUOIDUNG SET TENND = ? WHERE EMAILND = ?";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, tenND);
            pstmt.setString(2, email);

            // Thực thi câu lệnh cập nhật
            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                loadUserData(); // Refresh dữ liệu trên table_dsND
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật thông tin! Chi tiết: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Đóng kết nối sau khi thao tác xong
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Kết nối cơ sở dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_suaNDActionPerformed

    private void btn_searchNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchNDActionPerformed
        // TODO add your handling code here:
        String email = tf_nhaptenNDcantim.getText();

    // Kiểm tra nếu email không rỗng
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập email để tìm kiếm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Kết nối tới cơ sở dữ liệu
    connectToDatabase();

    if (connection != null) {
        try {
            // Tạo câu lệnh SQL để tìm kiếm người dùng theo email
            String sql = "SELECT * FROM NGUOIDUNG WHERE EMAILND = ?";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, email);

            // Thực thi câu lệnh truy vấn
            ResultSet rs = pstmt.executeQuery();

            // Xóa dữ liệu cũ trên bảng
            DefaultTableModel model = (DefaultTableModel) table_dsND.getModel();
            model.setRowCount(0);

            // Nếu tìm thấy người dùng, thêm vào bảng
            if (rs.next()) {
                Object[] row = {
                    rs.getString("EMAILND"),
                    rs.getString("TENND"),
                    // Thêm các cột khác nếu cần
                };
                model.addRow(row);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm người dùng! Chi tiết: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Đóng kết nối sau khi thao tác xong
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    } 
    else {
        JOptionPane.showMessageDialog(this, "Kết nối cơ sở dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    
    }//GEN-LAST:event_btn_searchNDActionPerformed

}
    private void btn_xoaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaNDActionPerformed
        // TODO add your handling code hereint
        // Lấy dòng được chọn trong bảng
    int selectedRow = table_dsND.getSelectedRow();

    // Kiểm tra nếu không có dòng nào được chọn
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một người dùng để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lấy email từ dòng được chọn
    DefaultTableModel model = (DefaultTableModel) table_dsND.getModel();
    String email = (String) model.getValueAt(selectedRow, 0); // Giả sử cột email là cột đầu tiên

    // Kết nối tới cơ sở dữ liệu
    connectToDatabase();

    if (connection != null) {
        try {
            // Gọi procedure để xóa người dùng và các thông tin liên quan
            String sql = "{call XOA_NGUOIDUNG (?)}";
            CallableStatement cstmt = connection.prepareCall(sql);
            cstmt.setString(1, email);

            // Thực thi procedure 
            cstmt.execute();

            JOptionPane.showMessageDialog(this, "Xóa người dùng thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            model.removeRow(selectedRow); // Xóa dòng khỏi bảng

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa người dùng! Chi tiết: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Đóng kết nối sau khi thao tác xong
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Kết nối cơ sở dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_xoaNDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ChatWindow dn = new ChatWindow();
        dn.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        panel_quanlitaikhoan.setVisible(false);
        panel_TK.setVisible(false);
        jpanel_ThongBao.setVisible(true);
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_TaothongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaothongbaoActionPerformed
        // TODO add your handling code here:
             String thongbao = txtA_thongbao.getText();

            // Kiểm tra xem nội dung tin nhắn có rỗng hay không
            if (!thongbao.isEmpty()) {
                ThongBaoDAO tb = new ThongBaoDAO();
                tb.ThemTB(thongbao);
                ghichu = "Có thông báo!";
                
                // Xóa nội dung thông báo từ text Area
                txtA_thongbao.setText("");

                displayMessages();
            } else {
                // Hiển thị thông báo lỗi nếu nội dung tin nhắn rỗng
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông báo!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btn_TaothongbaoActionPerformed

    private JPanel taoPanelTB(String thongbao) {
        JLabel thong_bao = new JLabel(thongbao);
        thong_bao.setOpaque(true);
        thong_bao.setBackground(Color.BLUE);
        thong_bao.setForeground(Color.WHITE);
        thong_bao.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.LEFT));
        panel.add(thong_bao);

        return panel;
    }
    
    private void displayMessages() {
        ThongBaoDAO thongbao = new ThongBaoDAO();
        List<ThongBaoDTO> danhSachThongBao = thongbao.layDanhSachTB();
        // Đặt layout manager cho panel_thongbao
        panel_thongbao.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.LINE_START;
        gbc.weightx = 1.0;
        gbc.gridx = 0;
        gbc.gridy = 0; // Bắt đầu từ dòng đầu tiên

        panel_thongbao.removeAll();
        // Hiển thị tất cả các thông báo trong danh sách
        for (ThongBaoDTO tb : danhSachThongBao) {
            if(tb != null){
                JPanel thongbaoPanel = taoPanelTB(tb.getTB());
                gbc.anchor = GridBagConstraints.LINE_START; // Căn trái
                panel_thongbao.add(thongbaoPanel, gbc);
                gbc.gridy++; // Chuyển sang dòng tiếp theo
            }
        }

        // Cập nhật giao diện người dùng
        panel_thongbao.revalidate();
        panel_thongbao.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                try {
                    new AdminHomepage().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AdminHomepage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_getEmailAD;
    private javax.swing.JTextField TF_getTenAD;
    private javax.swing.JTextField TF_tenND;
    private javax.swing.JButton btn_DX_TicTac;
    private javax.swing.JButton btn_DoiPass_TK;
    private javax.swing.JButton btn_Taothongbao;
    private javax.swing.JButton btn_searchND;
    private javax.swing.JButton btn_suaND;
    private javax.swing.JButton btn_xoaND;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jpanel_ThongBao;
    private javax.swing.JPanel panel_TK;
    private javax.swing.JPanel panel_quanlitaikhoan;
    private javax.swing.JPanel panel_thongbao;
    private javax.swing.JTable table_dsND;
    private javax.swing.JTextField tf_nhaptenNDcantim;
    private javax.swing.JTextArea txtA_thongbao;
    // End of variables declaration//GEN-END:variables
}
