/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ADMINDAO;
import DAO.NguoiDungDAO;
import DAO.NguoiDung_NhomDAO;
import DAO.NhomDAO;
import DAO.TinNhanDAO;
import DTO.ADMINDTO;
import DTO.NguoiDungDTO;
import DTO.NguoiDung_NhomDTO;
import DTO.TinNhanDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingConstants;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;

/**
 *
 * @author Oracle
 */
public class ChatWindow extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
        thongtinAd();
        addTableClickListener();
    }
    
    private void thongtinAd() {
        NguoiDung_NhomDAO nguoidung = new NguoiDung_NhomDAO();
        NhomDAO nhom = new NhomDAO();
        NguoiDungDAO nd = new NguoiDungDAO();
        String nd1 = nd.getTenNguoiDungByEmail(DangNhap.pEmail);
        DefaultTableModel model = (DefaultTableModel) table_danhsach.getModel();

        if(nd1 != null){
            String manhom = nhom.laymanhom(Homepage.tennhom);
            List<NguoiDung_NhomDTO> danhsachnd = nguoidung.layDanhSachTVTheoMaNhom(manhom);
            for(NguoiDung_NhomDTO nd_nhom : danhsachnd){
                model.insertRow(0, new Object[]{nd.getTenNguoiDungByEmail(nd_nhom.getEmailND()), nd_nhom.getEmailND()});
            }
        }
        else{
            ADMINDAO admin = new ADMINDAO();
            List<ADMINDTO> danhsachAd = admin.layDanhSachAd();
            for (ADMINDTO dsAdmin : danhsachAd) {
                model.insertRow(0, new Object[]{dsAdmin.getTenAd(), dsAdmin.getEmailAd()});
            }
        }
    }
    
    private void addTableClickListener() {
        table_danhsach.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = table_danhsach.getSelectedRow();
                if (row >= 0) {
                    String tenad = (String) table_danhsach.getValueAt(row, 0);
                    String emailad = (String) table_danhsach.getValueAt(row, 1);
                    jlable_tenad.setText(tenad);
                    displayMessages(DangNhap.pEmail, emailad); // Đặt email của admin hiện tại
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_danhsach = new javax.swing.JTable();
        tf_timkiem = new javax.swing.JTextField();
        btn_timkhiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_guitinnhan = new javax.swing.JButton();
        jlable_tenad = new javax.swing.JLabel();
        tf_tinnhan = new javax.swing.JTextField();
        scrollPane1 = new java.awt.ScrollPane();
        jpanel_tinnhan = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));

        table_danhsach.setBackground(new java.awt.Color(204, 255, 255));
        table_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Admin", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_danhsach.setGridColor(new java.awt.Color(153, 255, 255));
        jScrollPane1.setViewportView(table_danhsach);

        btn_timkhiem.setBackground(new java.awt.Color(204, 204, 255));
        btn_timkhiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_timkhiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkhiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timkhiem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_timkiem)
                    .addComponent(btn_timkhiem, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setOpaque(false);

        btn_guitinnhan.setBackground(new java.awt.Color(204, 204, 255));
        btn_guitinnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/send.png"))); // NOI18N
        btn_guitinnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guitinnhanActionPerformed(evt);
            }
        });

        jlable_tenad.setBackground(new java.awt.Color(204, 204, 255));
        jlable_tenad.setOpaque(true);

        jpanel_tinnhan.setBackground(new java.awt.Color(204, 255, 255));
        jpanel_tinnhan.setLayout(new java.awt.GridBagLayout());
        scrollPane1.add(jpanel_tinnhan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(tf_tinnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_guitinnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlable_tenad, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlable_tenad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guitinnhan, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(tf_tinnhan))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timkhiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkhiemActionPerformed
        // TODO add your handling code here:
        String ad = tf_timkiem.getText();
        // Kiểm tra nếu email không rỗng
        if (ad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên để tìm kiếm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) table_danhsach.getModel();
        
        ADMINDAO tim = new ADMINDAO();
        ADMINDTO tenAd = tim.TimAD(ad);
        
        if(tenAd != null){
            model.setRowCount(0);
            model.insertRow(0, new Object[]{ad, tenAd.getEmailAd()});
        }
        
        else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }     
      
    }//GEN-LAST:event_btn_timkhiemActionPerformed

    private void btn_guitinnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guitinnhanActionPerformed
         // Lấy chỉ mục của hàng đã chọn trong bảng Admin
        int row = table_danhsach.getSelectedRow();

        // Kiểm tra xem đã chọn hàng nào hay chưa
        if (row >= 0) {
            // Lấy email của người gửi tin nhắn
            String senderEmail = DangNhap.pEmail;

            // Lấy email của người nhận tin nhắn từ bảng Admin
            String receiverEmail = (String) table_danhsach.getValueAt(row, 1);

            // Lấy nội dung tin nhắn từ text field
            String tinnhan = tf_tinnhan.getText();

            // Kiểm tra xem nội dung tin nhắn có rỗng hay không
            if (!tinnhan.isEmpty()) {
                // Gửi tin nhắn
                TinNhanDAO tn = new TinNhanDAO();
                tn.sendMessage(senderEmail, receiverEmail, tinnhan);

                // Xóa nội dung tin nhắn từ text field sau khi đã gửi
                tf_tinnhan.setText("");

                // Hiển thị thông báo cho người dùng
                JOptionPane.showMessageDialog(this, "Tin nhắn đã được gửi!");

                // Cập nhật giao diện người dùng để hiển thị tin nhắn mới
                displayMessages(senderEmail, receiverEmail);
            } else {
                // Hiển thị thông báo lỗi nếu nội dung tin nhắn rỗng
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tin nhắn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn trong bảng Admin
            JOptionPane.showMessageDialog(this, "Vui lòng chọn admin để gửi tin nhắn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btn_guitinnhanActionPerformed

    private JPanel createSentMessagePanel(String messageText) {
        JLabel messageLabel = new JLabel(messageText);
        messageLabel.setOpaque(true);
        messageLabel.setBackground(Color.BLUE);
        messageLabel.setForeground(Color.WHITE);
        messageLabel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        panel.add(messageLabel);

        return panel;
    }

    private JPanel createReceivedMessagePanel(String messageText) {
        JLabel messageLabel = new JLabel(messageText);
        messageLabel.setOpaque(true);
        messageLabel.setBackground(Color.LIGHT_GRAY);
        messageLabel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.LEFT));
        panel.add(messageLabel);

        return panel;
    }

 

    private void displayMessages(String senderEmail, String receiverEmail) {
        TinNhanDAO tinnhanDAO = new TinNhanDAO();
        List<TinNhanDTO> tin_nhan = tinnhanDAO.getMessages(senderEmail, receiverEmail);

        // Đặt layout manager cho jpanel_tinnhan
        jpanel_tinnhan.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.LINE_START;
        gbc.weightx = 1.0;
        gbc.gridx = 0;
        gbc.gridy = 0; // Bắt đầu từ dòng đầu tiên

        // Xóa các tin nhắn hiện tại trên giao diện
        jpanel_tinnhan.removeAll();

        for (TinNhanDTO tn : tin_nhan) {
            JPanel messagePanel;
            if (tn.getSender().equals(senderEmail)) {
                // Tin nhắn của bạn: hiển thị bên phải
                messagePanel = createSentMessagePanel(tn.getText());
                gbc.anchor = GridBagConstraints.LINE_END; // Căn phải
            } else {
                // Tin nhắn của người nhận: hiển thị bên trái
                messagePanel = createReceivedMessagePanel(tn.getText());
                gbc.anchor = GridBagConstraints.LINE_START; // Căn trái
            }
            jpanel_tinnhan.add(messagePanel, gbc);
            gbc.gridy++; // Chuyển sang dòng tiếp theo
        }

        // Cập nhật giao diện người dùng
        jpanel_tinnhan.revalidate();
        jpanel_tinnhan.repaint();
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guitinnhan;
    private javax.swing.JButton btn_timkhiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlable_tenad;
    private javax.swing.JPanel jpanel_tinnhan;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable table_danhsach;
    private javax.swing.JTextField tf_timkiem;
    private javax.swing.JTextField tf_tinnhan;
    // End of variables declaration//GEN-END:variables
}
