/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NguoiDungDAO;
import DTO.NguoiDungDTO;
import javax.swing.JOptionPane;
import GUI.DangKi;

/**
 *
 * @author ASUS
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TicTac = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_VCT_TicTac = new javax.swing.JButton();
        btn_NCT_TicTac = new javax.swing.JButton();
        btn_TK_TicTac = new javax.swing.JButton();
        btn_DX_TicTac = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_VCT = new javax.swing.JPanel();
        tf_timcongviec_VCT = new javax.swing.JTextField();
        btn_TimKiem_VCT = new javax.swing.JButton();
        tabbedpane_BangCV_VCT = new javax.swing.JTabbedPane();
        panel_CanLam_BangCV_VCT = new javax.swing.JPanel();
        scrpane_CanLam_BangCV_VCT = new javax.swing.JScrollPane();
        table_CanLam_BangCV_VCT = new javax.swing.JTable();
        panel_DangLam_BangCV_VCT = new javax.swing.JPanel();
        scrpane_DangLam_BangCV_VCT = new javax.swing.JScrollPane();
        table_DangLam_BangCV_VCT = new javax.swing.JTable();
        panel_DaHoanThanh_BangCV_VCT = new javax.swing.JPanel();
        scrpane_DaHoanThanh_BangCV_VCT = new javax.swing.JScrollPane();
        table_DaHoanThanh_BangCV_VCT = new javax.swing.JTable();
        panel_NCT = new javax.swing.JPanel();
        tf_TimNhom_NCT = new javax.swing.JTextField();
        btn_TimNhom_NCt = new javax.swing.JButton();
        scrpane_DanhSachNhom_NCT = new javax.swing.JScrollPane();
        table_ThongTinNhom_NCT = new javax.swing.JTable();
        btn_TaoNhom_NCT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        scrpane_ThanhVien_TaoNhom = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panel_TK = new javax.swing.JPanel();
        label_TenNgDung_TK = new javax.swing.JLabel();
        label_MaNgDung_TK = new javax.swing.JLabel();
        tf_TenNgDung_TK = new javax.swing.JTextField();
        tf_Email_TK = new javax.swing.JTextField();
        btn_DoiPass_TK = new javax.swing.JButton();
        btn_XoaTK_TK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TicTac.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TicTac");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork (2).png"))); // NOI18N

        btn_VCT_TicTac.setBackground(new java.awt.Color(0, 0, 0));
        btn_VCT_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_VCT_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_VCT_TicTac.setText("Việc của tôi");
        btn_VCT_TicTac.setBorder(null);
        btn_VCT_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VCT_TicTacMouseClicked(evt);
            }
        });
        btn_VCT_TicTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VCT_TicTacActionPerformed(evt);
            }
        });

        btn_NCT_TicTac.setBackground(new java.awt.Color(0, 0, 0));
        btn_NCT_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_NCT_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_NCT_TicTac.setText("Nhóm của tôi");
        btn_NCT_TicTac.setBorder(null);
        btn_NCT_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NCT_TicTacMouseClicked(evt);
            }
        });
        btn_NCT_TicTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NCT_TicTacActionPerformed(evt);
            }
        });

        btn_TK_TicTac.setBackground(new java.awt.Color(0, 0, 0));
        btn_TK_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TK_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_TK_TicTac.setText("Tài khoản");
        btn_TK_TicTac.setBorder(null);
        btn_TK_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TK_TicTacMouseClicked(evt);
            }
        });
        btn_TK_TicTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TK_TicTacActionPerformed(evt);
            }
        });

        btn_DX_TicTac.setBackground(new java.awt.Color(0, 102, 102));
        btn_DX_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DX_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_DX_TicTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-out.png"))); // NOI18N
        btn_DX_TicTac.setText("Đăng xuất");
        btn_DX_TicTac.setToolTipText("");
        btn_DX_TicTac.setActionCommand("");
        btn_DX_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DX_TicTacMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TicTacLayout = new javax.swing.GroupLayout(TicTac);
        TicTac.setLayout(TicTacLayout);
        TicTacLayout.setHorizontalGroup(
            TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_VCT_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_NCT_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_TK_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TicTacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TicTacLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TicTacLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(btn_DX_TicTac)
                        .addGap(37, 37, 37))))
            .addGroup(TicTacLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TicTacLayout.setVerticalGroup(
            TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicTacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(btn_VCT_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_NCT_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_TK_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(btn_DX_TicTac)
                .addGap(17, 17, 17))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        panel_VCT.setBackground(new java.awt.Color(0, 102, 102));

        tf_timcongviec_VCT.setBackground(new java.awt.Color(0, 153, 153));
        tf_timcongviec_VCT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tf_timcongviec_VCT.setText("Nhập thông tin công việc");
        tf_timcongviec_VCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btn_TimKiem_VCT.setBackground(new java.awt.Color(0, 102, 102));
        btn_TimKiem_VCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_TimKiem_VCT.setBorder(null);
        btn_TimKiem_VCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_VCTActionPerformed(evt);
            }
        });

        tabbedpane_BangCV_VCT.setBackground(new java.awt.Color(0, 153, 153));
        tabbedpane_BangCV_VCT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        panel_CanLam_BangCV_VCT.setBackground(new java.awt.Color(204, 255, 204));

        table_CanLam_BangCV_VCT.setAutoCreateRowSorter(true);
        table_CanLam_BangCV_VCT.setBackground(new java.awt.Color(0, 153, 153));
        table_CanLam_BangCV_VCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_CanLam_BangCV_VCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên nhóm", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_CanLam_BangCV_VCT.setGridColor(new java.awt.Color(255, 255, 255));
        table_CanLam_BangCV_VCT.setSelectionBackground(new java.awt.Color(204, 255, 204));
        table_CanLam_BangCV_VCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_CanLam_BangCV_VCTMouseClicked(evt);
            }
        });
        scrpane_CanLam_BangCV_VCT.setViewportView(table_CanLam_BangCV_VCT);

        javax.swing.GroupLayout panel_CanLam_BangCV_VCTLayout = new javax.swing.GroupLayout(panel_CanLam_BangCV_VCT);
        panel_CanLam_BangCV_VCT.setLayout(panel_CanLam_BangCV_VCTLayout);
        panel_CanLam_BangCV_VCTLayout.setHorizontalGroup(
            panel_CanLam_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_CanLam_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        panel_CanLam_BangCV_VCTLayout.setVerticalGroup(
            panel_CanLam_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_CanLam_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tabbedpane_BangCV_VCT.addTab("Cần làm", panel_CanLam_BangCV_VCT);

        panel_DangLam_BangCV_VCT.setBackground(new java.awt.Color(204, 255, 204));

        table_DangLam_BangCV_VCT.setAutoCreateRowSorter(true);
        table_DangLam_BangCV_VCT.setBackground(new java.awt.Color(0, 153, 153));
        table_DangLam_BangCV_VCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_DangLam_BangCV_VCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên nhóm", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DangLam_BangCV_VCT.setGridColor(new java.awt.Color(255, 255, 255));
        table_DangLam_BangCV_VCT.setSelectionBackground(new java.awt.Color(204, 255, 204));
        scrpane_DangLam_BangCV_VCT.setViewportView(table_DangLam_BangCV_VCT);

        javax.swing.GroupLayout panel_DangLam_BangCV_VCTLayout = new javax.swing.GroupLayout(panel_DangLam_BangCV_VCT);
        panel_DangLam_BangCV_VCT.setLayout(panel_DangLam_BangCV_VCTLayout);
        panel_DangLam_BangCV_VCTLayout.setHorizontalGroup(
            panel_DangLam_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_DangLam_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        panel_DangLam_BangCV_VCTLayout.setVerticalGroup(
            panel_DangLam_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_DangLam_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tabbedpane_BangCV_VCT.addTab("Đang làm", panel_DangLam_BangCV_VCT);

        panel_DaHoanThanh_BangCV_VCT.setBackground(new java.awt.Color(204, 255, 204));

        table_DaHoanThanh_BangCV_VCT.setAutoCreateRowSorter(true);
        table_DaHoanThanh_BangCV_VCT.setBackground(new java.awt.Color(0, 153, 153));
        table_DaHoanThanh_BangCV_VCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_DaHoanThanh_BangCV_VCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên nhóm", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DaHoanThanh_BangCV_VCT.setGridColor(new java.awt.Color(255, 255, 255));
        table_DaHoanThanh_BangCV_VCT.setSelectionBackground(new java.awt.Color(204, 255, 204));
        scrpane_DaHoanThanh_BangCV_VCT.setViewportView(table_DaHoanThanh_BangCV_VCT);

        javax.swing.GroupLayout panel_DaHoanThanh_BangCV_VCTLayout = new javax.swing.GroupLayout(panel_DaHoanThanh_BangCV_VCT);
        panel_DaHoanThanh_BangCV_VCT.setLayout(panel_DaHoanThanh_BangCV_VCTLayout);
        panel_DaHoanThanh_BangCV_VCTLayout.setHorizontalGroup(
            panel_DaHoanThanh_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_DaHoanThanh_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        panel_DaHoanThanh_BangCV_VCTLayout.setVerticalGroup(
            panel_DaHoanThanh_BangCV_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpane_DaHoanThanh_BangCV_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tabbedpane_BangCV_VCT.addTab("Đã hoàn thành", panel_DaHoanThanh_BangCV_VCT);

        javax.swing.GroupLayout panel_VCTLayout = new javax.swing.GroupLayout(panel_VCT);
        panel_VCT.setLayout(panel_VCTLayout);
        panel_VCTLayout.setHorizontalGroup(
            panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_VCTLayout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addComponent(tf_timcongviec_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel_VCTLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tabbedpane_BangCV_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_VCTLayout.setVerticalGroup(
            panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_VCTLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_timcongviec_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_TimKiem_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(tabbedpane_BangCV_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panel_NCT.setBackground(new java.awt.Color(0, 102, 102));
        panel_NCT.setForeground(new java.awt.Color(255, 255, 255));

        tf_TimNhom_NCT.setBackground(new java.awt.Color(0, 153, 153));
        tf_TimNhom_NCT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tf_TimNhom_NCT.setText("Nhập thông tin nhóm");
        tf_TimNhom_NCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tf_TimNhom_NCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TimNhom_NCTActionPerformed(evt);
            }
        });

        btn_TimNhom_NCt.setBackground(new java.awt.Color(0, 102, 102));
        btn_TimNhom_NCt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_TimNhom_NCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimNhom_NCtActionPerformed(evt);
            }
        });

        table_ThongTinNhom_NCT.setAutoCreateRowSorter(true);
        table_ThongTinNhom_NCT.setBackground(new java.awt.Color(0, 153, 153));
        table_ThongTinNhom_NCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_ThongTinNhom_NCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tên nhóm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ThongTinNhom_NCT.setEnabled(false);
        scrpane_DanhSachNhom_NCT.setViewportView(table_ThongTinNhom_NCT);

        btn_TaoNhom_NCT.setBackground(new java.awt.Color(0, 102, 102));
        btn_TaoNhom_NCT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TaoNhom_NCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create.png"))); // NOI18N
        btn_TaoNhom_NCT.setText("Tạo nhóm");
        btn_TaoNhom_NCT.setBorder(null);
        btn_TaoNhom_NCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaoNhom_NCTMouseClicked(evt);
            }
        });
        btn_TaoNhom_NCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoNhom_NCTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên nhóm");

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Thành viên");

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.setText("jTextField2");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus_4315609 (1).png"))); // NOI18N

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Email", "Tên người dùng"
            }
        ));
        scrpane_ThanhVien_TaoNhom.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Xóa");

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Hoàn tác");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Rời nhóm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Thêm công việc");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_NCTLayout = new javax.swing.GroupLayout(panel_NCT);
        panel_NCT.setLayout(panel_NCTLayout);
        panel_NCTLayout.setHorizontalGroup(
            panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_NCTLayout.createSequentialGroup()
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_TaoNhom_NCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_TimNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_NCTLayout.createSequentialGroup()
                                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_NCTLayout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(scrpane_ThanhVien_TaoNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel_NCTLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(panel_NCTLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton7)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(scrpane_DanhSachNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimNhom_NCt)
                .addGap(23, 23, 23))
        );
        panel_NCTLayout.setVerticalGroup(
            panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NCTLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_TimNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimNhom_NCt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaoNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpane_DanhSachNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(9, 9, 9)
                        .addComponent(jButton5)
                        .addGap(9, 9, 9)
                        .addComponent(jButton6)
                        .addGap(3, 3, 3)))
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpane_ThanhVien_TaoNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton7)
                        .addGap(9, 9, 9)
                        .addComponent(jButton2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panel_TK.setBackground(new java.awt.Color(0, 102, 102));

        label_TenNgDung_TK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_TenNgDung_TK.setText("Tên người dùng");

        label_MaNgDung_TK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_MaNgDung_TK.setText("Email");

        tf_TenNgDung_TK.setBackground(new java.awt.Color(0, 153, 153));
        tf_TenNgDung_TK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_TenNgDung_TK.setBorder(null);
        tf_TenNgDung_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_TenNgDung_TKMouseClicked(evt);
            }
        });
        tf_TenNgDung_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenNgDung_TKActionPerformed(evt);
            }
        });

        tf_Email_TK.setBackground(new java.awt.Color(0, 153, 153));
        tf_Email_TK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Email_TK.setBorder(null);
        tf_Email_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Email_TKActionPerformed(evt);
            }
        });

        btn_DoiPass_TK.setBackground(new java.awt.Color(0, 102, 102));
        btn_DoiPass_TK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_DoiPass_TK.setText("Đổi mật khẩu");
        btn_DoiPass_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DoiPass_TKMouseClicked(evt);
            }
        });

        btn_XoaTK_TK.setBackground(new java.awt.Color(0, 102, 102));
        btn_XoaTK_TK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_XoaTK_TK.setText("Xóa tài khoản");
        btn_XoaTK_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaTK_TKMouseClicked(evt);
            }
        });
        btn_XoaTK_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTK_TKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TKLayout = new javax.swing.GroupLayout(panel_TK);
        panel_TK.setLayout(panel_TKLayout);
        panel_TKLayout.setHorizontalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_XoaTK_TK)
                    .addComponent(btn_DoiPass_TK))
                .addGap(339, 339, 339))
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_TenNgDung_TK)
                    .addComponent(label_MaNgDung_TK))
                .addGap(36, 36, 36)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_TenNgDung_TK)
                    .addComponent(tf_Email_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panel_TKLayout.setVerticalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_TenNgDung_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_TenNgDung_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_MaNgDung_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_Email_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btn_DoiPass_TK)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaTK_TK)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_NCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_NCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VCT_TicTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VCT_TicTacActionPerformed

    }//GEN-LAST:event_btn_VCT_TicTacActionPerformed

    private void btn_TK_TicTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TK_TicTacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TK_TicTacActionPerformed

    private void btn_VCT_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VCT_TicTacMouseClicked
        panel_VCT.setVisible(true);
        panel_NCT.setVisible(false);
        panel_TK.setVisible(false);
        
    }//GEN-LAST:event_btn_VCT_TicTacMouseClicked

    private void btn_NCT_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NCT_TicTacMouseClicked
        panel_NCT.setVisible(true);
        panel_VCT.setVisible(false);
        panel_TK.setVisible(false);

    }//GEN-LAST:event_btn_NCT_TicTacMouseClicked

    private void tf_TimNhom_NCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TimNhom_NCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TimNhom_NCTActionPerformed

    private void btn_TimNhom_NCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimNhom_NCtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimNhom_NCtActionPerformed

    private void btn_TK_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TK_TicTacMouseClicked
        panel_TK.setVisible(true);
        panel_VCT.setVisible(false);
        panel_NCT.setVisible(false);
    }//GEN-LAST:event_btn_TK_TicTacMouseClicked

    private void btn_NCT_TicTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NCT_TicTacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NCT_TicTacActionPerformed

    private void btn_TaoNhom_NCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaoNhom_NCTMouseClicked
       TaoNhom tn = new TaoNhom();
       tn.show();
    }//GEN-LAST:event_btn_TaoNhom_NCTMouseClicked

    private void btn_DoiPass_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoiPass_TKMouseClicked
        NhapEmail ne = new NhapEmail();
        ne.show();
        dispose();
    }//GEN-LAST:event_btn_DoiPass_TKMouseClicked

    private void btn_XoaTK_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTK_TKMouseClicked
        JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tài khoản vĩnh viễn?");
        DangKi dk = new DangKi();
        dk.show();
        dispose();
    }//GEN-LAST:event_btn_XoaTK_TKMouseClicked

    private void btn_DX_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DX_TicTacMouseClicked
        DangNhap dn = new DangNhap();
        dn.show();
        dispose();
    }//GEN-LAST:event_btn_DX_TicTacMouseClicked

    private void btn_TimKiem_VCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_VCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimKiem_VCTActionPerformed

    private void btn_TaoNhom_NCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoNhom_NCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoNhom_NCTActionPerformed

    private void tf_Email_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Email_TKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Email_TKActionPerformed

    private void tf_TenNgDung_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenNgDung_TKActionPerformed


    }//GEN-LAST:event_tf_TenNgDung_TKActionPerformed

    private void table_CanLam_BangCV_VCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_CanLam_BangCV_VCTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_CanLam_BangCV_VCTMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        TaoCongViec tcv = new TaoCongViec();
        tcv.show();
    }//GEN-LAST:event_jButton3MouseClicked

    private void btn_XoaTK_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTK_TKActionPerformed
 NguoiDungDAO nd = new NguoiDungDAO();
        NguoiDungDTO nd1=nd.xoataikhoan(tf_TenNgDung_TK.getText(),tf_Email_TK.getText());
         if (nd1==null)
        {
            JOptionPane.showMessageDialog(null, "tai khoan khong ton tai");

        }
        else {
             
            JOptionPane.showMessageDialog(null, " ban da xoa tai khoan tren thanh cong");
            DangNhap show = new DangNhap();
            show.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_XoaTK_TKActionPerformed

    private void tf_TenNgDung_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_TenNgDung_TKMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tf_TenNgDung_TKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TicTac;
    private javax.swing.JButton btn_DX_TicTac;
    private javax.swing.JButton btn_DoiPass_TK;
    private javax.swing.JButton btn_NCT_TicTac;
    private javax.swing.JButton btn_TK_TicTac;
    private javax.swing.JButton btn_TaoNhom_NCT;
    private javax.swing.JButton btn_TimKiem_VCT;
    private javax.swing.JButton btn_TimNhom_NCt;
    private javax.swing.JButton btn_VCT_TicTac;
    private javax.swing.JButton btn_XoaTK_TK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label_MaNgDung_TK;
    private javax.swing.JLabel label_TenNgDung_TK;
    private javax.swing.JPanel panel_CanLam_BangCV_VCT;
    private javax.swing.JPanel panel_DaHoanThanh_BangCV_VCT;
    private javax.swing.JPanel panel_DangLam_BangCV_VCT;
    private javax.swing.JPanel panel_NCT;
    private javax.swing.JPanel panel_TK;
    private javax.swing.JPanel panel_VCT;
    private javax.swing.JScrollPane scrpane_CanLam_BangCV_VCT;
    private javax.swing.JScrollPane scrpane_DaHoanThanh_BangCV_VCT;
    private javax.swing.JScrollPane scrpane_DangLam_BangCV_VCT;
    private javax.swing.JScrollPane scrpane_DanhSachNhom_NCT;
    private javax.swing.JScrollPane scrpane_ThanhVien_TaoNhom;
    private javax.swing.JTabbedPane tabbedpane_BangCV_VCT;
    private javax.swing.JTable table_CanLam_BangCV_VCT;
    private javax.swing.JTable table_DaHoanThanh_BangCV_VCT;
    private javax.swing.JTable table_DangLam_BangCV_VCT;
    private javax.swing.JTable table_ThongTinNhom_NCT;
    private javax.swing.JTextField tf_Email_TK;
    private javax.swing.JTextField tf_TenNgDung_TK;
    private javax.swing.JTextField tf_TimNhom_NCT;
    private javax.swing.JTextField tf_timcongviec_VCT;
    // End of variables declaration//GEN-END:variables
}
