/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

/**
 *
 * @author ASUS
 */
public class NhapEmail extends javax.swing.JFrame {

    /**
     * Creates new form NhapEmail
     */
    public NhapEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_OTP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_Email_OTP = new javax.swing.JLabel();
        tf_Email_OTP = new javax.swing.JTextField();
        btn_NhanEmail_OTP = new javax.swing.JButton();
        label_OTP_OTP = new javax.swing.JLabel();
        tf_OTP_OTP = new javax.swing.JTextField();
        btn_Xong_OTP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_OTP.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to TicTac");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork (2).png"))); // NOI18N

        label_Email_OTP.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label_Email_OTP.setForeground(new java.awt.Color(255, 255, 255));
        label_Email_OTP.setText("Email");

        tf_Email_OTP.setBackground(new java.awt.Color(0, 102, 102));
        tf_Email_OTP.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tf_Email_OTP.setForeground(new java.awt.Color(255, 255, 255));
        tf_Email_OTP.setText("Nhập email để nhận OTP");
        tf_Email_OTP.setToolTipText("");

        btn_NhanEmail_OTP.setBackground(new java.awt.Color(0, 102, 102));
        btn_NhanEmail_OTP.setForeground(new java.awt.Color(255, 255, 255));
        btn_NhanEmail_OTP.setText("Nhận");
        btn_NhanEmail_OTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanEmail_OTPActionPerformed(evt);
            }
        });

        label_OTP_OTP.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label_OTP_OTP.setForeground(new java.awt.Color(255, 255, 255));
        label_OTP_OTP.setText("OTP");

        tf_OTP_OTP.setBackground(new java.awt.Color(0, 102, 102));
        tf_OTP_OTP.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        btn_Xong_OTP.setBackground(new java.awt.Color(0, 102, 102));
        btn_Xong_OTP.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xong_OTP.setText("Xong");
        btn_Xong_OTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Xong_OTPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_OTPLayout = new javax.swing.GroupLayout(panel_OTP);
        panel_OTP.setLayout(panel_OTPLayout);
        panel_OTPLayout.setHorizontalGroup(
            panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_OTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(panel_OTPLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(panel_OTPLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Email_OTP)
                    .addComponent(label_OTP_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_OTPLayout.createSequentialGroup()
                        .addComponent(tf_Email_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_NhanEmail_OTP))
                    .addGroup(panel_OTPLayout.createSequentialGroup()
                        .addComponent(tf_OTP_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_Xong_OTP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_OTPLayout.setVerticalGroup(
            panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_OTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Email_OTP)
                    .addComponent(tf_Email_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhanEmail_OTP))
                .addGap(18, 18, 18)
                .addGroup(panel_OTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_OTP_OTP)
                    .addComponent(tf_OTP_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xong_OTP))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_OTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_OTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Xong_OTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Xong_OTPMouseClicked
        TaoMKMoi tmkm = new TaoMKMoi();
        tmkm.show();
        dispose();
    }//GEN-LAST:event_btn_Xong_OTPMouseClicked

    private void btn_NhanEmail_OTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanEmail_OTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhanEmail_OTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NhanEmail_OTP;
    private javax.swing.JButton btn_Xong_OTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_Email_OTP;
    private javax.swing.JLabel label_OTP_OTP;
    private javax.swing.JPanel panel_OTP;
    private javax.swing.JTextField tf_Email_OTP;
    private javax.swing.JTextField tf_OTP_OTP;
    // End of variables declaration//GEN-END:variables
}
