/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static javax.swing.UIManager.getString;
import DTO.NhomDTO;
import DAO.CongViecDAO;
import DAO.NguoiDung_NhomDAO;
import DAO.NhomDAO;
import DAO.ThucHienDAO;
import DTO.CongViecDTO;
import DTO.NguoiDung_NhomDTO;
import DTO.ThucHienDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.get;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TaoCongViec extends javax.swing.JFrame {
    public static String emailtv;
    

    /**
     * Creates new form TaoCongViec
     */
    public TaoCongViec() {
        initComponents();
        thongtinNPT();
        addTableClickListener();

    }
    private void thongtinNPT() {
        NguoiDung_NhomDAO tv = new NguoiDung_NhomDAO();
        List<NguoiDung_NhomDTO> danhSachTV = tv.layDanhSachTVTheoMaNhom(Homepage.mn);
        DefaultTableModel model = (DefaultTableModel) table_NguoiPT.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng hiện có trong bảng

        for (NguoiDung_NhomDTO tvien : danhSachTV) {
            model.addRow(new Object[]{tvien.getEmailND()});
        }
    }
    
    private void addTableClickListener() {
        table_NguoiPT.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = table_NguoiPT.getSelectedRow();
                if (row >= 0) {
                    String email = (String) table_NguoiPT.getValueAt(row, 0);
                    tf_NguoiPT_TaoCV.setText(email);
                    emailtv = email;
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_TaoCV = new javax.swing.JPanel();
        label_TaoCV = new javax.swing.JLabel();
        label_TenCV_TaoCV = new javax.swing.JLabel();
        label_LinhVuc_TaCV = new javax.swing.JLabel();
        label_MoTa_TaoCV = new javax.swing.JLabel();
        label_MDUT_TaoCV = new javax.swing.JLabel();
        label_NgayBD_TaoCV = new javax.swing.JLabel();
        label_NgayKT_TaoCV = new javax.swing.JLabel();
        tf_TenCV_TaoCV = new javax.swing.JTextField();
        tf_LinhVuc_TaoCV = new javax.swing.JTextField();
        scrpane_MoTa_TaoCV = new javax.swing.JScrollPane();
        textarea_MoTa_TaoCV = new javax.swing.JTextArea();
        combobox_MDUT_TaoCV = new javax.swing.JComboBox<>();
        label_NguoiPT_TaoCV = new javax.swing.JLabel();
        btn_HoanThanh_TaoCV = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        tf_NguoiPT_TaoCV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_NguoiPT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_TaoCV.setBackground(new java.awt.Color(109, 129, 245));

        label_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_TaoCV.setText("Tạo công việc mới");

        label_TenCV_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_TenCV_TaoCV.setText("Tên công việc");

        label_LinhVuc_TaCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_LinhVuc_TaCV.setText("Lĩnh vực");

        label_MoTa_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_MoTa_TaoCV.setText("Mô tả");

        label_MDUT_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_MDUT_TaoCV.setText("Mức độ ưu tiên");

        label_NgayBD_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_NgayBD_TaoCV.setText("Ngày bắt đầu");

        label_NgayKT_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_NgayKT_TaoCV.setText("Ngày kết thúc");

        tf_TenCV_TaoCV.setBackground(new java.awt.Color(182, 231, 245));
        tf_TenCV_TaoCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenCV_TaoCVActionPerformed(evt);
            }
        });

        tf_LinhVuc_TaoCV.setBackground(new java.awt.Color(182, 231, 245));

        textarea_MoTa_TaoCV.setBackground(new java.awt.Color(182, 231, 245));
        textarea_MoTa_TaoCV.setColumns(20);
        textarea_MoTa_TaoCV.setRows(5);
        scrpane_MoTa_TaoCV.setViewportView(textarea_MoTa_TaoCV);

        combobox_MDUT_TaoCV.setBackground(new java.awt.Color(182, 231, 245));
        combobox_MDUT_TaoCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Cần gấp", "2. Quan trọng", "3. Thường" }));
        combobox_MDUT_TaoCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_MDUT_TaoCVActionPerformed(evt);
            }
        });

        label_NguoiPT_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_NguoiPT_TaoCV.setText("Chọn người phụ trách");

        btn_HoanThanh_TaoCV.setBackground(new java.awt.Color(49, 141, 245));
        btn_HoanThanh_TaoCV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_HoanThanh_TaoCV.setText("Hoàn thành");
        btn_HoanThanh_TaoCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HoanThanh_TaoCVMouseClicked(evt);
            }
        });
        btn_HoanThanh_TaoCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoanThanh_TaoCVActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(182, 231, 245));
        jDateChooser1.setDateFormatString("dd MMM yyyy");

        jDateChooser2.setBackground(new java.awt.Color(182, 231, 245));
        jDateChooser2.setDateFormatString("dd MMM yyyy");

        tf_NguoiPT_TaoCV.setBackground(new java.awt.Color(182, 231, 245));

        table_NguoiPT.setBackground(new java.awt.Color(182, 231, 245));
        table_NguoiPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_NguoiPT);

        javax.swing.GroupLayout panel_TaoCVLayout = new javax.swing.GroupLayout(panel_TaoCV);
        panel_TaoCV.setLayout(panel_TaoCVLayout);
        panel_TaoCVLayout.setHorizontalGroup(
            panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_TaoCVLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(label_TaoCV))
                    .addGroup(panel_TaoCVLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_TenCV_TaoCV)
                                    .addComponent(label_LinhVuc_TaCV)
                                    .addComponent(label_MoTa_TaoCV))
                                .addGap(18, 18, 18)
                                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_TenCV_TaoCV)
                                    .addComponent(tf_LinhVuc_TaoCV)
                                    .addComponent(scrpane_MoTa_TaoCV, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                                .addComponent(label_NgayBD_TaoCV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(label_NgayKT_TaoCV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                                .addComponent(label_NguoiPT_TaoCV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_NguoiPT_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                                .addComponent(label_MDUT_TaoCV)
                                .addGap(40, 40, 40)
                                .addComponent(combobox_MDUT_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_TaoCVLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btn_HoanThanh_TaoCV)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TaoCVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        panel_TaoCVLayout.setVerticalGroup(
            panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TaoCVLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_TaoCV)
                .addGap(18, 18, 18)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_TenCV_TaoCV)
                    .addComponent(tf_TenCV_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_LinhVuc_TaCV)
                    .addGroup(panel_TaoCVLayout.createSequentialGroup()
                        .addComponent(tf_LinhVuc_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_MoTa_TaoCV)
                    .addComponent(scrpane_MoTa_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MDUT_TaoCV)
                    .addComponent(combobox_MDUT_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_NgayBD_TaoCV)
                    .addComponent(label_NgayKT_TaoCV)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_TaoCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_NguoiPT_TaoCV)
                    .addComponent(tf_NguoiPT_TaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_HoanThanh_TaoCV)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_TaoCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_TaoCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void combobox_MDUT_TaoCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_MDUT_TaoCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_MDUT_TaoCVActionPerformed

    private void btn_HoanThanh_TaoCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HoanThanh_TaoCVMouseClicked
        Homepage hp = new Homepage();
        hp.show();
        dispose();
    }//GEN-LAST:event_btn_HoanThanh_TaoCVMouseClicked

    private void tf_TenCV_TaoCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenCV_TaoCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenCV_TaoCVActionPerformed

    private void btn_HoanThanh_TaoCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoanThanh_TaoCVActionPerformed
        if (tf_TenCV_TaoCV.getText().isEmpty() || tf_LinhVuc_TaoCV.getText().isEmpty() ||
        combobox_MDUT_TaoCV.getSelectedItem() == null || textarea_MoTa_TaoCV.getText().isEmpty() ||
        jDateChooser1.getDate() == null || jDateChooser2.getDate() == null || tf_NguoiPT_TaoCV.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Chưa nhập đủ thông tin cần thiết");
    } else {
        // Chuyển đổi ngày từ JDateChooser sang String
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBD = sdf.format(jDateChooser1.getDate());
        String ngayKT = sdf.format(jDateChooser2.getDate());
        String manh = Homepage.laymanhom;
        
        // Tạo một instance của CongViecDAO và thử thêm công việc
        CongViecDAO themcv = new CongViecDAO();
        ThucHienDAO themthcv = new ThucHienDAO();
        CongViecDTO cv = themcv.ThemCV(
            Homepage.laymanhom,
            tf_TenCV_TaoCV.getText(),
            tf_LinhVuc_TaoCV.getText(),
            textarea_MoTa_TaoCV.getText(),
            (String) combobox_MDUT_TaoCV.getSelectedItem(),
            ngayBD,
            ngayKT
        );
        String macv = themcv.laymacv(manh, tf_TenCV_TaoCV.getText());
        
        // Kiểm tra kết quả và cập nhật UI tương ứng
        if (cv != null) {
            JOptionPane.showMessageDialog(this, "Công việc đã được tạo thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            ThucHienDTO thhuchien = themthcv.themthuchien(emailtv, macv, manh, "Cần làm");
            
            // Mở cửa sổ Homepage và đóng cửa sổ hiện tại
            Homepage home = new Homepage();
            home.setVisible(true);
            dispose();
        } 
        else {
            JOptionPane.showMessageDialog(this, "Tạo công việc thất bại. Vui lòng kiểm tra lại thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btn_HoanThanh_TaoCVActionPerformed


public void ViewTable(){
        DefaultTableModel model = (DefaultTableModel) this.table_NguoiPT.getModel();
        
    }
    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoCongViec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HoanThanh_TaoCV;
    private javax.swing.JComboBox<String> combobox_MDUT_TaoCV;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_LinhVuc_TaCV;
    private javax.swing.JLabel label_MDUT_TaoCV;
    private javax.swing.JLabel label_MoTa_TaoCV;
    private javax.swing.JLabel label_NgayBD_TaoCV;
    private javax.swing.JLabel label_NgayKT_TaoCV;
    private javax.swing.JLabel label_NguoiPT_TaoCV;
    private javax.swing.JLabel label_TaoCV;
    private javax.swing.JLabel label_TenCV_TaoCV;
    private javax.swing.JPanel panel_TaoCV;
    private javax.swing.JScrollPane scrpane_MoTa_TaoCV;
    private javax.swing.JTable table_NguoiPT;
    private javax.swing.JTextArea textarea_MoTa_TaoCV;
    private javax.swing.JTextField tf_LinhVuc_TaoCV;
    private javax.swing.JTextField tf_NguoiPT_TaoCV;
    private javax.swing.JTextField tf_TenCV_TaoCV;
    // End of variables declaration//GEN-END:variables
}
