/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.CongViecDAO;
import DAO.FileAttachmentDAO;
import DAO.NhomDAO;
import DAO.ThucHienDAO;
import DTO.CongViecDTO;
import DTO.FileAttachmentDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultListModel;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Oracle
 */
public class XemTienDoCongViec extends javax.swing.JFrame {

    /**
     * Creates new form XemTienDoCongViec
     */
    public XemTienDoCongViec() {
        initComponents();
        try {
            Xemthongtin();
        } catch (ParseException ex) {
            Logger.getLogger(XemTienDoCongViec.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Xemthongtin() throws ParseException{
        String tencv = ChiTietNhom.tencv;
        String nguoiphutrach = ChiTietNhom.nguoiphutrach;
        ThucHienDAO thuchien = new ThucHienDAO();
        NhomDAO nhom = new NhomDAO();
        String ma_nhom = nhom.laymanhom(tencv);
        String laymacv = thuchien.laymacvtheonguoiphutrach(nguoiphutrach, ma_nhom);
        CongViecDAO congviec = new CongViecDAO();
        CongViecDTO congvieccanlam = congviec.TimCV(laymacv);
        if (congvieccanlam != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            jlabel_tencv_ChiTietCongViec.setText(congvieccanlam.getTenCV());
            tf_Mota_Chitietcongviec.setText(congvieccanlam.getMoTa());
            jlabel_linhvuc_ChiTietCongViec.setText(congvieccanlam.getLinhVuc());
            jlabel_mucuutien_ChiTietCongViec.setText(String.valueOf(congvieccanlam.getMuc_uutien()));
            jlabel_ngaybd_ChiTietCongViec.setText(dateFormat.format(congvieccanlam.getNgayBD()));
            jlabel_ngaykt_ChiTietCongViec.setText(dateFormat.format(congvieccanlam.getNgayKT()));
            FileAttachmentDAO file = new FileAttachmentDAO();
            List<FileAttachmentDTO> danhSachfile = file.layDanhSachFileTheoMacv(laymacv);
            if (danhSachfile != null && !danhSachfile.isEmpty()) {
                DefaultListModel<String> model = new DefaultListModel<>();
                for (FileAttachmentDTO ds : danhSachfile) {
                    model.addElement(ds.getDuongDan());
                }
                list_file_TienDo.setModel(model);
                } 
            else {
                // Xử lý khi không có file đính kèm
                DefaultListModel<String> model = new DefaultListModel<>();
                model.addElement("Không có file đính kèm");
                list_file_TienDo.setModel(model);
            }
        }
        else {
            // Xử lý khi công việc không tồn tại
            jlabel_tencv_ChiTietCongViec.setText("Công việc không tồn tại");
            tf_Mota_Chitietcongviec.setText("");
            jlabel_linhvuc_ChiTietCongViec.setText("");
            jlabel_mucuutien_ChiTietCongViec.setText("");
            jlabel_ngaybd_ChiTietCongViec.setText("");
            jlabel_ngaykt_ChiTietCongViec.setText("");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabel_tencongviec = new javax.swing.JLabel();
        jlabel_tencv_ChiTietCongViec = new javax.swing.JLabel();
        jlabel_mota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_Mota_Chitietcongviec = new javax.swing.JTextArea();
        jlabel_linhvuc = new javax.swing.JLabel();
        jlabel_linhvuc_ChiTietCongViec = new javax.swing.JLabel();
        jlabel_mucuutien = new javax.swing.JLabel();
        jlabel_mucuutien_ChiTietCongViec = new javax.swing.JLabel();
        jlabel_ngaybd = new javax.swing.JLabel();
        jlabel_ngaybd_ChiTietCongViec = new javax.swing.JLabel();
        jlabel_ngaykt = new javax.swing.JLabel();
        jlabel_ngaykt_ChiTietCongViec = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_file_TienDo = new javax.swing.JList<>();
        jlabel_Trangthaicongviec = new javax.swing.JLabel();
        jcombobox_trangthai = new javax.swing.JComboBox<>();
        btn_HoanThanh_ChiTiecCongViec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jlabel_tencongviec.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_tencongviec.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_tencongviec.setText("Tên công việc");

        jlabel_tencv_ChiTietCongViec.setBackground(new java.awt.Color(255, 255, 204));
        jlabel_tencv_ChiTietCongViec.setText("jLabel1");
        jlabel_tencv_ChiTietCongViec.setOpaque(true);

        jlabel_mota.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_mota.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_mota.setText("Mô tả");

        tf_Mota_Chitietcongviec.setBackground(new java.awt.Color(255, 255, 204));
        tf_Mota_Chitietcongviec.setColumns(20);
        tf_Mota_Chitietcongviec.setRows(5);
        tf_Mota_Chitietcongviec.setBorder(null);
        jScrollPane1.setViewportView(tf_Mota_Chitietcongviec);

        jlabel_linhvuc.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_linhvuc.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_linhvuc.setText("Lĩnh vực");

        jlabel_linhvuc_ChiTietCongViec.setBackground(new java.awt.Color(255, 255, 204));
        jlabel_linhvuc_ChiTietCongViec.setText("jLabel2");
        jlabel_linhvuc_ChiTietCongViec.setOpaque(true);

        jlabel_mucuutien.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_mucuutien.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_mucuutien.setText("Mức độ ưu tiên");

        jlabel_mucuutien_ChiTietCongViec.setBackground(new java.awt.Color(255, 255, 204));
        jlabel_mucuutien_ChiTietCongViec.setText("jLabel3");
        jlabel_mucuutien_ChiTietCongViec.setOpaque(true);

        jlabel_ngaybd.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_ngaybd.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_ngaybd.setText("Ngày bắt đầu");

        jlabel_ngaybd_ChiTietCongViec.setBackground(new java.awt.Color(255, 255, 204));
        jlabel_ngaybd_ChiTietCongViec.setText("jLabel4");
        jlabel_ngaybd_ChiTietCongViec.setOpaque(true);

        jlabel_ngaykt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_ngaykt.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_ngaykt.setText("Ngày kết thúc");

        jlabel_ngaykt_ChiTietCongViec.setBackground(new java.awt.Color(255, 255, 204));
        jlabel_ngaykt_ChiTietCongViec.setText("jLabel5");
        jlabel_ngaykt_ChiTietCongViec.setOpaque(true);

        list_file_TienDo.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane2.setViewportView(list_file_TienDo);

        jlabel_Trangthaicongviec.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel_Trangthaicongviec.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Trangthaicongviec.setText("Trạng thái công việc");

        jcombobox_trangthai.setBackground(new java.awt.Color(0, 153, 153));
        jcombobox_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cần làm", "đang làm", "đã hoàn thành" }));

        btn_HoanThanh_ChiTiecCongViec.setBackground(new java.awt.Color(0, 51, 51));
        btn_HoanThanh_ChiTiecCongViec.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_HoanThanh_ChiTiecCongViec.setForeground(new java.awt.Color(255, 255, 255));
        btn_HoanThanh_ChiTiecCongViec.setText("Hoàn thành");
        btn_HoanThanh_ChiTiecCongViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoanThanh_ChiTiecCongViecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btn_HoanThanh_ChiTiecCongViec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabel_Trangthaicongviec)
                        .addGap(44, 44, 44)
                        .addComponent(jcombobox_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabel_mota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabel_ngaybd)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabel_ngaybd_ChiTietCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabel_linhvuc)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabel_linhvuc_ChiTietCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlabel_ngaykt)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_ngaykt_ChiTietCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabel_tencongviec)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlabel_tencv_ChiTietCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabel_mucuutien)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabel_mucuutien_ChiTietCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(319, 319, 319)))))
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_tencongviec)
                    .addComponent(jlabel_tencv_ChiTietCongViec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_mota)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_linhvuc)
                    .addComponent(jlabel_linhvuc_ChiTietCongViec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_mucuutien)
                    .addComponent(jlabel_mucuutien_ChiTietCongViec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_ngaybd)
                    .addComponent(jlabel_ngaykt)
                    .addComponent(jlabel_ngaybd_ChiTietCongViec)
                    .addComponent(jlabel_ngaykt_ChiTietCongViec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_Trangthaicongviec)
                    .addComponent(jcombobox_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btn_HoanThanh_ChiTiecCongViec)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HoanThanh_ChiTiecCongViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoanThanh_ChiTiecCongViecActionPerformed
        // TODO add your handling code here:
        ChiTietNhom nhom = new ChiTietNhom();
        nhom.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_HoanThanh_ChiTiecCongViecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemTienDoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemTienDoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemTienDoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemTienDoCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemTienDoCongViec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HoanThanh_ChiTiecCongViec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcombobox_trangthai;
    private javax.swing.JLabel jlabel_Trangthaicongviec;
    private javax.swing.JLabel jlabel_linhvuc;
    private javax.swing.JLabel jlabel_linhvuc_ChiTietCongViec;
    private javax.swing.JLabel jlabel_mota;
    private javax.swing.JLabel jlabel_mucuutien;
    private javax.swing.JLabel jlabel_mucuutien_ChiTietCongViec;
    private javax.swing.JLabel jlabel_ngaybd;
    private javax.swing.JLabel jlabel_ngaybd_ChiTietCongViec;
    private javax.swing.JLabel jlabel_ngaykt;
    private javax.swing.JLabel jlabel_ngaykt_ChiTietCongViec;
    private javax.swing.JLabel jlabel_tencongviec;
    private javax.swing.JLabel jlabel_tencv_ChiTietCongViec;
    private javax.swing.JList<String> list_file_TienDo;
    private javax.swing.JTextArea tf_Mota_Chitietcongviec;
    // End of variables declaration//GEN-END:variables
}
