/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

/**
 *
 * @author ASUS
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TicTac = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_VCT_TicTac = new javax.swing.JButton();
        btn_NCT_TicTac = new javax.swing.JButton();
        btn_TK_TicTac = new javax.swing.JButton();
        btn_DX_TicTac = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_VCT = new javax.swing.JPanel();
        tf_timcongviec_VCT = new javax.swing.JTextField();
        btn_TimKiem_VCT = new javax.swing.JButton();
        tablepane_TimCongViec_VCT = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        Scrpane_TimCongViec_VCT = new javax.swing.JScrollPane();
        table_TimCongViec_VCT = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        panel_NCT = new javax.swing.JPanel();
        tf_ThongTinNhom_NCT = new javax.swing.JTextField();
        btn_TimNhom_NCT = new javax.swing.JButton();
        Scrtable_TaoNhom_NCT = new javax.swing.JScrollPane();
        table_TaoNhom_NCT = new javax.swing.JTable();
        btn_TaoNhom_NCT = new javax.swing.JButton();
        panel_ThemNhom_NCT = new javax.swing.JPanel();
        label_ThemNhom_ThemNhom = new javax.swing.JLabel();
        lb_MaNhom_ThemNhom = new javax.swing.JLabel();
        tf_MaNhom_ThemNhom = new javax.swing.JTextField();
        label_TenNhom_ThemNhom = new javax.swing.JLabel();
        tf_TenNhom_ThemNhom = new javax.swing.JTextField();
        label_ThemEmail_ThemNhom = new javax.swing.JLabel();
        tf_Email_ThemNhom = new javax.swing.JTextField();
        btn_ThemEmail_ThemNhom = new javax.swing.JButton();
        Scrpane_danhsachthanhvien_ThemNhom = new javax.swing.JScrollPane();
        table_ThemThanhVien_ThemNhom = new javax.swing.JTable();
        btn_Xong_ThemNhom = new javax.swing.JButton();
        panel_TK = new javax.swing.JPanel();
        label_TenNguoiDung_TK = new javax.swing.JLabel();
        label_MaNguoiDung_Tk = new javax.swing.JLabel();
        tf_TenNguoiDung_TK = new javax.swing.JTextField();
        tf_MaNguoiDung_TK = new javax.swing.JTextField();
        btn_DoiMatkhau_TK = new javax.swing.JButton();
        btn_XoaTaiKhoan_TK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TicTac.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TicTac");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork (2).png"))); // NOI18N

        btn_VCT_TicTac.setBackground(new java.awt.Color(0, 102, 102));
        btn_VCT_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_VCT_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_VCT_TicTac.setText("Việc của tôi");
        btn_VCT_TicTac.setBorder(null);
        btn_VCT_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VCT_TicTacMouseClicked(evt);
            }
        });
        btn_VCT_TicTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VCT_TicTacActionPerformed(evt);
            }
        });

        btn_NCT_TicTac.setBackground(new java.awt.Color(0, 102, 102));
        btn_NCT_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_NCT_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_NCT_TicTac.setText("Nhóm của tôi");
        btn_NCT_TicTac.setBorder(null);
        btn_NCT_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NCT_TicTacMouseClicked(evt);
            }
        });

        btn_TK_TicTac.setBackground(new java.awt.Color(0, 102, 102));
        btn_TK_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TK_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_TK_TicTac.setText("Tài khoản");
        btn_TK_TicTac.setBorder(null);
        btn_TK_TicTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TK_TicTacMouseClicked(evt);
            }
        });
        btn_TK_TicTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TK_TicTacActionPerformed(evt);
            }
        });

        btn_DX_TicTac.setBackground(new java.awt.Color(0, 102, 102));
        btn_DX_TicTac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DX_TicTac.setForeground(new java.awt.Color(255, 255, 255));
        btn_DX_TicTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log-out.png"))); // NOI18N
        btn_DX_TicTac.setText("Đăng xuất");
        btn_DX_TicTac.setToolTipText("");
        btn_DX_TicTac.setActionCommand("");

        javax.swing.GroupLayout TicTacLayout = new javax.swing.GroupLayout(TicTac);
        TicTac.setLayout(TicTacLayout);
        TicTacLayout.setHorizontalGroup(
            TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_VCT_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_NCT_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_TK_TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TicTacLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TicTacLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TicTacLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TicTacLayout.createSequentialGroup()
                        .addComponent(btn_DX_TicTac)
                        .addGap(37, 37, 37))))
        );
        TicTacLayout.setVerticalGroup(
            TicTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicTacLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(btn_VCT_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_NCT_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_TK_TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(btn_DX_TicTac)
                .addGap(17, 17, 17))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        panel_VCT.setBackground(new java.awt.Color(204, 255, 204));

        tf_timcongviec_VCT.setBackground(new java.awt.Color(255, 255, 204));
        tf_timcongviec_VCT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tf_timcongviec_VCT.setText("Nhập thông tin công việc");
        tf_timcongviec_VCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btn_TimKiem_VCT.setBackground(new java.awt.Color(204, 255, 204));
        btn_TimKiem_VCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_TimKiem_VCT.setBorder(null);

        tablepane_TimCongViec_VCT.setBackground(new java.awt.Color(204, 255, 204));
        tablepane_TimCongViec_VCT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        table_TimCongViec_VCT.setAutoCreateRowSorter(true);
        table_TimCongViec_VCT.setBackground(new java.awt.Color(204, 255, 204));
        table_TimCongViec_VCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_TimCongViec_VCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã công việc", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TimCongViec_VCT.setGridColor(new java.awt.Color(255, 255, 255));
        table_TimCongViec_VCT.setSelectionBackground(new java.awt.Color(204, 255, 204));
        Scrpane_TimCongViec_VCT.setViewportView(table_TimCongViec_VCT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scrpane_TimCongViec_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scrpane_TimCongViec_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tablepane_TimCongViec_VCT.addTab("Cần làm", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jTable5.setAutoCreateRowSorter(true);
        jTable5.setBackground(new java.awt.Color(204, 255, 204));
        jTable5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã công việc", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setGridColor(new java.awt.Color(255, 255, 255));
        jTable5.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tablepane_TimCongViec_VCT.addTab("Đang làm", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jTable6.setAutoCreateRowSorter(true);
        jTable6.setBackground(new java.awt.Color(204, 255, 204));
        jTable6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã công việc", "Tên công việc", "Lĩnh vực", "Mô tả", "Ngày bắt đầu", "Ngày kết thúc", "Mức độ ưu tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.setGridColor(new java.awt.Color(255, 255, 255));
        jTable6.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        tablepane_TimCongViec_VCT.addTab("Đã hoàn thành", jPanel7);

        javax.swing.GroupLayout panel_VCTLayout = new javax.swing.GroupLayout(panel_VCT);
        panel_VCT.setLayout(panel_VCTLayout);
        panel_VCTLayout.setHorizontalGroup(
            panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_VCTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_timcongviec_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(panel_VCTLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tablepane_TimCongViec_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        panel_VCTLayout.setVerticalGroup(
            panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_VCTLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_VCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TimKiem_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tf_timcongviec_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablepane_TimCongViec_VCT, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        panel_NCT.setBackground(new java.awt.Color(204, 255, 204));

        tf_ThongTinNhom_NCT.setBackground(new java.awt.Color(255, 255, 204));
        tf_ThongTinNhom_NCT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tf_ThongTinNhom_NCT.setText("Nhập thông tin nhóm");
        tf_ThongTinNhom_NCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tf_ThongTinNhom_NCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ThongTinNhom_NCTActionPerformed(evt);
            }
        });

        btn_TimNhom_NCT.setBackground(new java.awt.Color(204, 255, 204));
        btn_TimNhom_NCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btn_TimNhom_NCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimNhom_NCTActionPerformed(evt);
            }
        });

        table_TaoNhom_NCT.setAutoCreateRowSorter(true);
        table_TaoNhom_NCT.setBackground(new java.awt.Color(204, 255, 204));
        table_TaoNhom_NCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_TaoNhom_NCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã nhóm", "Tên nhóm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TaoNhom_NCT.setEnabled(false);
        table_TaoNhom_NCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_TaoNhom_NCTMouseClicked(evt);
            }
        });
        Scrtable_TaoNhom_NCT.setViewportView(table_TaoNhom_NCT);

        btn_TaoNhom_NCT.setBackground(new java.awt.Color(204, 255, 204));
        btn_TaoNhom_NCT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TaoNhom_NCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create.png"))); // NOI18N
        btn_TaoNhom_NCT.setText("Tạo nhóm");
        btn_TaoNhom_NCT.setBorder(null);
        btn_TaoNhom_NCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaoNhom_NCTMouseClicked(evt);
            }
        });
        btn_TaoNhom_NCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoNhom_NCTActionPerformed(evt);
            }
        });

        panel_ThemNhom_NCT.setBackground(new java.awt.Color(255, 255, 204));

        label_ThemNhom_ThemNhom.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label_ThemNhom_ThemNhom.setText("THÊM NHÓM LÀM VIỆC");

        lb_MaNhom_ThemNhom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_MaNhom_ThemNhom.setText("Mã nhóm");

        tf_MaNhom_ThemNhom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_MaNhom_ThemNhom.setText("Nhập mã nhóm");
        tf_MaNhom_ThemNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MaNhom_ThemNhomActionPerformed(evt);
            }
        });

        label_TenNhom_ThemNhom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_TenNhom_ThemNhom.setText("Tên nhóm");

        tf_TenNhom_ThemNhom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_TenNhom_ThemNhom.setText("Nhập tên nhóm");

        label_ThemEmail_ThemNhom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_ThemEmail_ThemNhom.setText("Thêm thành viên");

        tf_Email_ThemNhom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Email_ThemNhom.setText("Email thành viên");

        btn_ThemEmail_ThemNhom.setBackground(new java.awt.Color(255, 255, 204));
        btn_ThemEmail_ThemNhom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus_4315609 (1).png"))); // NOI18N

        table_ThemThanhVien_ThemNhom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Danh sách thành viên trong nhóm"
            }
        ));
        Scrpane_danhsachthanhvien_ThemNhom.setViewportView(table_ThemThanhVien_ThemNhom);

        btn_Xong_ThemNhom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Xong_ThemNhom.setText("Xong");
        btn_Xong_ThemNhom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Xong_ThemNhomMouseClicked(evt);
            }
        });
        btn_Xong_ThemNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xong_ThemNhomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ThemNhom_NCTLayout = new javax.swing.GroupLayout(panel_ThemNhom_NCT);
        panel_ThemNhom_NCT.setLayout(panel_ThemNhom_NCTLayout);
        panel_ThemNhom_NCTLayout.setHorizontalGroup(
            panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ThemNhom_NCTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_ThemNhom_ThemNhom)
                .addGap(141, 141, 141))
            .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                        .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_ThemEmail_ThemNhom)
                            .addComponent(lb_MaNhom_ThemNhom))
                        .addGap(30, 30, 30)
                        .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Email_ThemNhom, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(tf_MaNhom_ThemNhom))
                        .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(label_TenNhom_ThemNhom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_TenNhom_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ThemEmail_ThemNhom)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                        .addComponent(Scrpane_danhsachthanhvien_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Xong_ThemNhom)
                        .addGap(59, 59, 59))))
        );
        panel_ThemNhom_NCTLayout.setVerticalGroup(
            panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(label_ThemNhom_ThemNhom)
                .addGap(54, 54, 54)
                .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MaNhom_ThemNhom)
                    .addComponent(tf_MaNhom_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TenNhom_ThemNhom)
                    .addComponent(tf_TenNhom_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel_ThemNhom_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_ThemEmail_ThemNhom)
                            .addComponent(tf_Email_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemEmail_ThemNhom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(Scrpane_danhsachthanhvien_ThemNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ThemNhom_NCTLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Xong_ThemNhom)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout panel_NCTLayout = new javax.swing.GroupLayout(panel_NCT);
        panel_NCT.setLayout(panel_NCTLayout);
        panel_NCTLayout.setHorizontalGroup(
            panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_NCTLayout.createSequentialGroup()
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addContainerGap(314, Short.MAX_VALUE)
                        .addComponent(Scrtable_TaoNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_NCTLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_TaoNhom_NCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_ThongTinNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimNhom_NCT)
                .addGap(23, 23, 23))
            .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_NCTLayout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(panel_ThemNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );
        panel_NCTLayout.setVerticalGroup(
            panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NCTLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_ThongTinNhom_NCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_TimNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_TaoNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Scrtable_TaoNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(panel_NCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_NCTLayout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(panel_ThemNhom_NCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        panel_TK.setBackground(new java.awt.Color(204, 255, 204));

        label_TenNguoiDung_TK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_TenNguoiDung_TK.setText("Tên người dùng");

        label_MaNguoiDung_Tk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_MaNguoiDung_Tk.setText("Mã người dùng");

        tf_TenNguoiDung_TK.setBackground(new java.awt.Color(204, 255, 204));
        tf_TenNguoiDung_TK.setText("jTextField3");
        tf_TenNguoiDung_TK.setBorder(null);

        tf_MaNguoiDung_TK.setBackground(new java.awt.Color(204, 255, 204));
        tf_MaNguoiDung_TK.setText("jTextField4");
        tf_MaNguoiDung_TK.setBorder(null);

        btn_DoiMatkhau_TK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_DoiMatkhau_TK.setText("Đổi mật khẩu");

        btn_XoaTaiKhoan_TK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_XoaTaiKhoan_TK.setText("Xóa tài khoản");

        javax.swing.GroupLayout panel_TKLayout = new javax.swing.GroupLayout(panel_TK);
        panel_TK.setLayout(panel_TKLayout);
        panel_TKLayout.setHorizontalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_XoaTaiKhoan_TK)
                    .addComponent(btn_DoiMatkhau_TK))
                .addGap(339, 339, 339))
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_TenNguoiDung_TK)
                    .addComponent(label_MaNguoiDung_Tk))
                .addGap(36, 36, 36)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_TenNguoiDung_TK)
                    .addComponent(tf_MaNguoiDung_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panel_TKLayout.setVerticalGroup(
            panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TKLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_TenNguoiDung_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_TenNguoiDung_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_MaNguoiDung_Tk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_MaNguoiDung_TK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btn_DoiMatkhau_TK)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaTaiKhoan_TK)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_NCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_VCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_NCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_TK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TicTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TicTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VCT_TicTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VCT_TicTacActionPerformed
        panel_VCT.setVisible(true);
    }//GEN-LAST:event_btn_VCT_TicTacActionPerformed

    private void btn_TK_TicTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TK_TicTacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TK_TicTacActionPerformed

    private void btn_VCT_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VCT_TicTacMouseClicked
        panel_VCT.setVisible(true);
        panel_NCT.setVisible(false);
        panel_TK.setVisible(false);

    }//GEN-LAST:event_btn_VCT_TicTacMouseClicked

    private void btn_NCT_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NCT_TicTacMouseClicked
        panel_VCT.setVisible(false);
        panel_NCT.setVisible(true);
        panel_TK.setVisible(false);
        panel_ThemNhom_NCT.setVisible(false);


    }//GEN-LAST:event_btn_NCT_TicTacMouseClicked

    private void tf_ThongTinNhom_NCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ThongTinNhom_NCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ThongTinNhom_NCTActionPerformed

    private void btn_TimNhom_NCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimNhom_NCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimNhom_NCTActionPerformed

    private void btn_TK_TicTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TK_TicTacMouseClicked
        panel_VCT.setVisible(false);
        panel_NCT.setVisible(false);
        panel_TK.setVisible(true);

    }//GEN-LAST:event_btn_TK_TicTacMouseClicked

    private void btn_TaoNhom_NCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaoNhom_NCTMouseClicked
        // TODO add your handling code here:
        panel_VCT.setVisible(false);
        panel_NCT.setVisible(true);
        table_TaoNhom_NCT.setVisible(false);
        panel_TK.setVisible(false);
        panel_ThemNhom_NCT.setVisible(true);
        Scrtable_TaoNhom_NCT.setVisible(false);
    }//GEN-LAST:event_btn_TaoNhom_NCTMouseClicked

    private void table_TaoNhom_NCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_TaoNhom_NCTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_TaoNhom_NCTMouseClicked

    private void btn_TaoNhom_NCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoNhom_NCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoNhom_NCTActionPerformed

    private void tf_MaNhom_ThemNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MaNhom_ThemNhomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaNhom_ThemNhomActionPerformed

    private void btn_Xong_ThemNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xong_ThemNhomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Xong_ThemNhomActionPerformed

    private void btn_Xong_ThemNhomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Xong_ThemNhomMouseClicked
        // TODO add your handling code here:
          panel_VCT.setVisible(true);
        panel_NCT.setVisible(true);
        table_TaoNhom_NCT.setVisible(true);
        panel_TK.setVisible(true);
        panel_ThemNhom_NCT.setVisible(false);
        Scrtable_TaoNhom_NCT.setVisible(true);
    }//GEN-LAST:event_btn_Xong_ThemNhomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrpane_TimCongViec_VCT;
    private javax.swing.JScrollPane Scrpane_danhsachthanhvien_ThemNhom;
    private javax.swing.JScrollPane Scrtable_TaoNhom_NCT;
    private javax.swing.JPanel TicTac;
    private javax.swing.JButton btn_DX_TicTac;
    private javax.swing.JButton btn_DoiMatkhau_TK;
    private javax.swing.JButton btn_NCT_TicTac;
    private javax.swing.JButton btn_TK_TicTac;
    private javax.swing.JButton btn_TaoNhom_NCT;
    private javax.swing.JButton btn_ThemEmail_ThemNhom;
    private javax.swing.JButton btn_TimKiem_VCT;
    private javax.swing.JButton btn_TimNhom_NCT;
    private javax.swing.JButton btn_VCT_TicTac;
    private javax.swing.JButton btn_XoaTaiKhoan_TK;
    private javax.swing.JButton btn_Xong_ThemNhom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel label_MaNguoiDung_Tk;
    private javax.swing.JLabel label_TenNguoiDung_TK;
    private javax.swing.JLabel label_TenNhom_ThemNhom;
    private javax.swing.JLabel label_ThemEmail_ThemNhom;
    private javax.swing.JLabel label_ThemNhom_ThemNhom;
    private javax.swing.JLabel lb_MaNhom_ThemNhom;
    private javax.swing.JPanel panel_NCT;
    private javax.swing.JPanel panel_TK;
    private javax.swing.JPanel panel_ThemNhom_NCT;
    private javax.swing.JPanel panel_VCT;
    private javax.swing.JTable table_TaoNhom_NCT;
    private javax.swing.JTable table_ThemThanhVien_ThemNhom;
    private javax.swing.JTable table_TimCongViec_VCT;
    private javax.swing.JTabbedPane tablepane_TimCongViec_VCT;
    private javax.swing.JTextField tf_Email_ThemNhom;
    private javax.swing.JTextField tf_MaNguoiDung_TK;
    private javax.swing.JTextField tf_MaNhom_ThemNhom;
    private javax.swing.JTextField tf_TenNguoiDung_TK;
    private javax.swing.JTextField tf_TenNhom_ThemNhom;
    private javax.swing.JTextField tf_ThongTinNhom_NCT;
    private javax.swing.JTextField tf_timcongviec_VCT;
    // End of variables declaration//GEN-END:variables
}
